### ISSUE TITLE
List a single todo by ID

### ISSUE THREAD

**Issue by Keenan-04** [UMM-CSci-3601-F24/lab-2-john-el#2]
Implement an `api/todos/58895985c1849992336c219b` server-side endpoint, which
        returns the single todo with the given `_id`. It should return a 404
        (use the Javalin `NotFoundResponse` class) if there is no todo with the
        specified `_id`.

**Comment by Bonesbhbhbh** [comment]
only works if you change your url, does not work through reg search feature
